<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Previous student report based on the rnaseqGene Bioconductor workflow">

<title>RNA-seq analysis with Bioconductor</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="analysis_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analysis_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analysis_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul class="collapse">
  <li><a href="#experimental-data" id="toc-experimental-data" class="nav-link" data-scroll-target="#experimental-data">Experimental Data</a></li>
  </ul></li>
  <li><a href="#preparing-quantification-input-to-deseq2" id="toc-preparing-quantification-input-to-deseq2" class="nav-link" data-scroll-target="#preparing-quantification-input-to-deseq2">Preparing quantification input to DESeq2</a>
  <ul class="collapse">
  <li><a href="#snakemake" id="toc-snakemake" class="nav-link" data-scroll-target="#snakemake">Snakemake</a></li>
  <li><a href="#reading-in-data-with-tximeta" id="toc-reading-in-data-with-tximeta" class="nav-link" data-scroll-target="#reading-in-data-with-tximeta">Reading in data with tximeta</a></li>
  <li><a href="#summarizedexperiment-object" id="toc-summarizedexperiment-object" class="nav-link" data-scroll-target="#summarizedexperiment-object">SummarizedExperiment object</a></li>
  <li><a href="#summarize-to-gene-level" id="toc-summarize-to-gene-level" class="nav-link" data-scroll-target="#summarize-to-gene-level">summarize to gene level</a></li>
  <li><a href="#gse-from-airway" id="toc-gse-from-airway" class="nav-link" data-scroll-target="#gse-from-airway">gse from airway</a></li>
  </ul></li>
  <li><a href="#deseqdataset" id="toc-deseqdataset" class="nav-link" data-scroll-target="#deseqdataset">DESeqDataSet</a></li>
  <li><a href="#exploratory-analysis-and-visualization" id="toc-exploratory-analysis-and-visualization" class="nav-link" data-scroll-target="#exploratory-analysis-and-visualization">Exploratory analysis and visualization</a>
  <ul class="collapse">
  <li><a href="#prefiltering" id="toc-prefiltering" class="nav-link" data-scroll-target="#prefiltering">Prefiltering</a></li>
  <li><a href="#variance-stabilizing-transformation-and-the-rlog" id="toc-variance-stabilizing-transformation-and-the-rlog" class="nav-link" data-scroll-target="#variance-stabilizing-transformation-and-the-rlog">Variance stabilizing transformation and the rlog</a></li>
  <li><a href="#sample-distances" id="toc-sample-distances" class="nav-link" data-scroll-target="#sample-distances">Sample distances</a></li>
  <li><a href="#heatmap-pheatmap-sample-distances-using-variance-stabilizing-transformation" id="toc-heatmap-pheatmap-sample-distances-using-variance-stabilizing-transformation" class="nav-link" data-scroll-target="#heatmap-pheatmap-sample-distances-using-variance-stabilizing-transformation">Heatmap (Pheatmap) sample distances using variance stabilizing transformation</a></li>
  <li><a href="#heat-map-sample-distances-using-poisson-distance" id="toc-heat-map-sample-distances-using-poisson-distance" class="nav-link" data-scroll-target="#heat-map-sample-distances-using-poisson-distance">Heat map sample distances using Poisson distance</a></li>
  <li><a href="#pca-plot-vst-data" id="toc-pca-plot-vst-data" class="nav-link" data-scroll-target="#pca-plot-vst-data">PCA plot (VST data)</a></li>
  <li><a href="#generalized-pca-plot" id="toc-generalized-pca-plot" class="nav-link" data-scroll-target="#generalized-pca-plot">Generalized PCA plot</a></li>
  <li><a href="#mds-plot" id="toc-mds-plot" class="nav-link" data-scroll-target="#mds-plot">MDS plot</a></li>
  </ul></li>
  <li><a href="#differential-expression-analysis" id="toc-differential-expression-analysis" class="nav-link" data-scroll-target="#differential-expression-analysis">Differential expression analysis</a></li>
  <li><a href="#plotting-results" id="toc-plotting-results" class="nav-link" data-scroll-target="#plotting-results">Plotting results</a>
  <ul class="collapse">
  <li><a href="#counts-plot" id="toc-counts-plot" class="nav-link" data-scroll-target="#counts-plot">Counts plot</a></li>
  <li><a href="#ma-plot" id="toc-ma-plot" class="nav-link" data-scroll-target="#ma-plot">MA-plot</a></li>
  <li><a href="#gene-clustering" id="toc-gene-clustering" class="nav-link" data-scroll-target="#gene-clustering">Gene clustering</a></li>
  </ul></li>
  <li><a href="#annotating-and-exporting-results" id="toc-annotating-and-exporting-results" class="nav-link" data-scroll-target="#annotating-and-exporting-results">Annotating and exporting results</a>
  <ul class="collapse">
  <li><a href="#exporting-results" id="toc-exporting-results" class="nav-link" data-scroll-target="#exporting-results">Exporting results</a></li>
  <li><a href="#plotting-fold-changes-in-genomic-space" id="toc-plotting-fold-changes-in-genomic-space" class="nav-link" data-scroll-target="#plotting-fold-changes-in-genomic-space">Plotting fold changes in genomic space</a></li>
  </ul></li>
  <li><a href="#removing-hidden-batch-effects" id="toc-removing-hidden-batch-effects" class="nav-link" data-scroll-target="#removing-hidden-batch-effects">Removing hidden batch effects</a>
  <ul class="collapse">
  <li><a href="#using-sva-with-deseq2" id="toc-using-sva-with-deseq2" class="nav-link" data-scroll-target="#using-sva-with-deseq2">Using SVA with DESeq2</a></li>
  <li><a href="#using-ruv-with-deseq2" id="toc-using-ruv-with-deseq2" class="nav-link" data-scroll-target="#using-ruv-with-deseq2">Using RUV with DESeq2</a></li>
  </ul></li>
  <li><a href="#time-course-experiments" id="toc-time-course-experiments" class="nav-link" data-scroll-target="#time-course-experiments">Time course experiments</a></li>
  <li><a href="#session-information" id="toc-session-information" class="nav-link" data-scroll-target="#session-information">Session information</a>
  <ul class="collapse">
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">RNA-seq analysis with Bioconductor</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Previous student report based on the rnaseqGene Bioconductor workflow </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>This Quarto document reproduces, as an academic exercise, the Bioconductor workflow package <a href="https://www.bioconductor.org/packages/release/workflows/html/rnaseqGene.html">rnaseqGene</a> using the recommended alternative pipeline utilizing Salmon for transcript quantification <span class="citation" data-cites="love_rna-seq_2016">(<a href="#ref-love_rna-seq_2016" role="doc-biblioref">Michael I. Love et al. 2016</a>)</span>. The <a href="https://www.bioconductor.org/packages/release/workflows/html/rnaseqGene.html">rnaseqGene</a> workflow package uses the data in the <a href="https://www.bioconductor.org/packages/release/data/experiment/html/airway.html">airway</a> package to demonstrate an end-to-end workflow for an RNA sequencing experiment <span class="citation" data-cites="himes_rna-seq_2014">(<a href="#ref-himes_rna-seq_2014" role="doc-biblioref">Himes et al. 2014</a>)</span>.</p>
<p>The recommended alternative pipeline demonstration will use Salmon for transcript quantification of the FASTQ reads. The quantification files produced by Salmon are loaded into the package <a href="https://www.bioconductor.org/packages/release/bioc/html/tximeta.html">tximeta</a>, which will provide genomic annotation and create the Bioconductor friendly data container SummarizedExperiment <span class="citation" data-cites="love_tximeta_2020">(<a href="#ref-love_tximeta_2020" role="doc-biblioref">Michael I. Love et al. 2020</a>)</span>. The SummarizedExperiment data container are loaded into DESeq2 to create the data object DESeqDataSet, which is used for analysis.</p>
<section id="experimental-data" class="level3">
<h3 class="anchored" data-anchor-id="experimental-data">Experimental Data</h3>
<p>Included with the <a href="https://www.bioconductor.org/packages/release/data/experiment/html/airway.html">airway</a> package are eight BAM files (each BAM file is a subset of the total reads for demonstration purposes), a small subset of a gene transfer format (GTF) annotation file relevant for the subset BAM files, a full count matrix corresponding to all experimental data, a sample table in CSV format, and two FASTQ files <span class="citation" data-cites="himes_rna-seq_2014">(<a href="#ref-himes_rna-seq_2014" role="doc-biblioref">Himes et al. 2014</a>)</span>.</p>
<p>The experimental data comes from Human airway smooth muscle (HASM) cell lines isolated from 4 healthy white male aborted lung transplant donors. The cell lines were treated with Dexamethasone or a control vehicle for 18 hours.</p>
</section>
</section>
<section id="preparing-quantification-input-to-deseq2" class="level2">
<h2 class="anchored" data-anchor-id="preparing-quantification-input-to-deseq2">Preparing quantification input to DESeq2</h2>
<p>The recommended pipeline is to use Salmon to quantify transcript abundance. The <a href="https://www.bioconductor.org/packages/release/workflows/html/rnaseqGene.html">rnaseqGene</a> workflow vignette recommends this guide <a href="https://combine-lab.github.io/salmon/getting_started/" class="uri">https://combine-lab.github.io/salmon/getting_started/</a> to use Salmon to produce plain-text, tab-separated quant.sf files. Quant.sf files contain the following: Name of target transcript, length of target transcript in nucleotides, EffectiveLength, Transcripts Per Million (TPM), and NumReads (Salmon’s estimate of the number of reads mapping to each transcript that was quantified).</p>
<section id="snakemake" class="level3">
<h3 class="anchored" data-anchor-id="snakemake">Snakemake</h3>
<p>The following Snakemake file text is provided by the <a href="https://www.bioconductor.org/packages/release/workflows/html/rnaseqGene.html">rnaseqGene</a> vingette.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>DATASETS <span class="op">=</span> [<span class="st">"SRR1039508"</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>            <span class="st">"SRR1039509"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>            <span class="st">"SRR1039512"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">"SRR1039513"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">"SRR1039516"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">"SRR1039517"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">"SRR1039520"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">"SRR1039521"</span>]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>SALMON <span class="op">=</span> <span class="st">"/path/to/salmon_0.14.1/bin/salmon"</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>rule <span class="bu">all</span>:</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="bu">input</span>: expand(<span class="st">"quants/</span><span class="sc">{dataset}</span><span class="st">/quant.sf"</span>, dataset<span class="op">=</span>DATASETS)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>rule salmon_quant:</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">input</span>:</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>        r1 <span class="op">=</span> <span class="st">"fastq/</span><span class="sc">{sample}</span><span class="st">_1.fastq.gz"</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>        r2 <span class="op">=</span> <span class="st">"fastq/</span><span class="sc">{sample}</span><span class="st">_2.fastq.gz"</span>,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>        index <span class="op">=</span> <span class="st">"/path/to/gencode.v29_salmon_0.14.1"</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    output:</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>        <span class="co">"quants/{sample}/quant.sf"</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    params:</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>        <span class="bu">dir</span> <span class="op">=</span> <span class="st">"quants/</span><span class="sc">{sample}</span><span class="st">"</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    shell:</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>        <span class="co">"{SALMON} quant -i {input.index} -l A -p 6 --validateMappings </span><span class="op">\</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co">         --gcBias --numGibbsSamples 20 -o {params.dir} </span><span class="op">\</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co">         -1 {input.r1} -2 {input.r2}"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The Snakemake file requires the eight runs with the listed SRR IDs to be downloaded from the Sequence Read Archive and for an index to be created at:</p>
<p><code>/path/to/gencode.vVV_salmon_X.Y.Z</code></p>
<p>VV stands for the specific release of the reference transcripts (e.g.&nbsp;47) and X.Y.Z stands for the specific release of Salmon.</p>
<p>The Salmon index can be created with the command:</p>
<p><code>salmon index -t transcripts.fa.gz -i name_of_index</code></p>
<p>The <a href="https://www.bioconductor.org/packages/release/workflows/html/rnaseqGene.html">rnaseqGene</a> vingette recommends the use of genomic decoy sequences (see Salmon’s <a href="https://salmon.readthedocs.io/en/latest/salmon.html#preparing-transcriptome-indices-mapping-based-mode">documentation</a>) to improve quantification accuracy, as demonstrated by Srivastava et al (2020). The human reference transcriptome can be obtained from <a href="https://www.gencodegenes.org/">GENCODE</a>.</p>
</section>
<section id="reading-in-data-with-tximeta" class="level3">
<h3 class="anchored" data-anchor-id="reading-in-data-with-tximeta">Reading in data with tximeta</h3>
<p>The transcript quantification files produced by Salmon can be brought into the bioconductor environment using <a href="https://www.bioconductor.org/packages/release/bioc/html/tximeta.html">tximeta</a> to produce the SummarizedExperiment data object <span class="citation" data-cites="love_tximeta_2020">(<a href="#ref-love_tximeta_2020" role="doc-biblioref">Michael I. Love et al. 2020</a>)</span>. To demonstrate with the <a href="https://www.bioconductor.org/packages/release/data/experiment/html/airway.html">airway</a> package <span class="citation" data-cites="himes_rna-seq_2014">(<a href="#ref-himes_rna-seq_2014" role="doc-biblioref">Himes et al. 2014</a>)</span>, the following code loads the <a href="https://www.bioconductor.org/packages/release/data/experiment/html/airway.html">airway</a> library, identifies and assigns the variable “dir” to represent the local directories that contain the quant.sf Salmon files. The <a href="https://www.bioconductor.org/packages/release/data/experiment/html/airway.html">airway</a> package only provides two quant.sf files for runs SRR1039508 and SRR1039509 for demonstrative purposes.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## loadairway</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"airway"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="do">## dir</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>dir <span class="ot">&lt;-</span> <span class="fu">system.file</span>(<span class="st">"extdata"</span>, <span class="at">package=</span><span class="st">"airway"</span>, <span class="at">mustWork=</span><span class="cn">TRUE</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="do">## list.files</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">list.files</span>(dir)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "GSE52778_series_matrix.txt"        "Homo_sapiens.GRCh37.75_subset.gtf"
 [3] "quants"                            "sample_table.csv"                 
 [5] "SraRunInfo_SRP033351.csv"          "SRR1039508_subset.bam"            
 [7] "SRR1039509_subset.bam"             "SRR1039512_subset.bam"            
 [9] "SRR1039513_subset.bam"             "SRR1039516_subset.bam"            
[11] "SRR1039517_subset.bam"             "SRR1039520_subset.bam"            
[13] "SRR1039521_subset.bam"            </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list.files</span>(<span class="fu">file.path</span>(dir, <span class="st">"quants"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "SRR1039508" "SRR1039509"</code></pre>
</div>
</div>
<p><a href="https://www.bioconductor.org/packages/release/bioc/html/tximeta.html">tximeta</a> requires a CSV or TSV sample table. The <a href="https://www.bioconductor.org/packages/release/data/experiment/html/airway.html">airway</a> package provides an example of a sample table containing important sample identifying information, such as Sample Name, treatment/condition, sequencing run, and other conditions and identifying information for each sample.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">## sampleinfo</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>csvfile <span class="ot">&lt;-</span> <span class="fu">file.path</span>(dir, <span class="st">"sample_table.csv"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>coldata <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(csvfile, <span class="at">row.names=</span><span class="dv">1</span>, <span class="at">stringsAsFactors=</span><span class="cn">FALSE</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>coldata</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           SampleName    cell   dex albut        Run avgLength Experiment
SRR1039508 GSM1275862  N61311 untrt untrt SRR1039508       126  SRX384345
SRR1039509 GSM1275863  N61311   trt untrt SRR1039509       126  SRX384346
SRR1039512 GSM1275866 N052611 untrt untrt SRR1039512       126  SRX384349
SRR1039513 GSM1275867 N052611   trt untrt SRR1039513        87  SRX384350
SRR1039516 GSM1275870 N080611 untrt untrt SRR1039516       120  SRX384353
SRR1039517 GSM1275871 N080611   trt untrt SRR1039517       126  SRX384354
SRR1039520 GSM1275874 N061011 untrt untrt SRR1039520       101  SRX384357
SRR1039521 GSM1275875 N061011   trt untrt SRR1039521        98  SRX384358
              Sample    BioSample
SRR1039508 SRS508568 SAMN02422669
SRR1039509 SRS508567 SAMN02422675
SRR1039512 SRS508571 SAMN02422678
SRR1039513 SRS508572 SAMN02422670
SRR1039516 SRS508575 SAMN02422682
SRR1039517 SRS508576 SAMN02422673
SRR1039520 SRS508579 SAMN02422683
SRR1039521 SRS508580 SAMN02422677</code></pre>
</div>
</div>
<p>However, <a href="https://www.bioconductor.org/packages/release/bioc/html/tximeta.html">tximeta</a> requires a sample table with at least two columns provided as: “files” and “names”. “files” will contain a pointer to the quant.sf files. “names” will contain unique names that identify samples.</p>
<p>The sample table provided by <a href="https://www.bioconductor.org/packages/release/data/experiment/html/airway.html">airway</a> does not contain these two required columns (“names” and “files”). We create these required columns with the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="do">##makecoldata</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#this code for vignette loading salmon quant on select samples</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>coldata <span class="ot">&lt;-</span> coldata[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,]</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>coldata<span class="sc">$</span>names <span class="ot">&lt;-</span> coldata<span class="sc">$</span>Run</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>coldata<span class="sc">$</span>files <span class="ot">&lt;-</span> <span class="fu">file.path</span>(dir, <span class="st">"quants"</span>, coldata<span class="sc">$</span>names, <span class="st">"quant.sf.gz"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">file.exists</span>(coldata<span class="sc">$</span>files)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>coldata</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           SampleName   cell   dex albut        Run avgLength Experiment
SRR1039508 GSM1275862 N61311 untrt untrt SRR1039508       126  SRX384345
SRR1039509 GSM1275863 N61311   trt untrt SRR1039509       126  SRX384346
              Sample    BioSample      names
SRR1039508 SRS508568 SAMN02422669 SRR1039508
SRR1039509 SRS508567 SAMN02422675 SRR1039509
                                                                                                   files
SRR1039508 C:/Users/johnson/AppData/Local/R/win-library/4.5/airway/extdata/quants/SRR1039508/quant.sf.gz
SRR1039509 C:/Users/johnson/AppData/Local/R/win-library/4.5/airway/extdata/quants/SRR1039509/quant.sf.gz</code></pre>
</div>
</div>
<p>Once our sample table has been updated properly to point to the quant.sf files and the sample name for each file, we can run <a href="https://www.bioconductor.org/packages/release/bioc/html/tximeta.html">tximeta</a> to produce the SummarizedExperiment object with this simple code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tximeta"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">tximeta</span>(coldata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>importing salmon quantification files</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>reading in files with read_tsv</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>1 2 
found matching transcriptome:
[ GENCODE - Homo sapiens - release 29 ]
loading existing TxDb created: 2026-04-11 18:49:24
Loading required package: GenomicFeatures
loading existing transcript ranges created: 2026-04-11 18:49:26</code></pre>
</div>
</div>
<p>The dimensions and rownames of the SummarizedExperiment object can be viewed with this code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(se)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 205870      2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">rownames</span>(se))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ENST00000456328.2" "ENST00000450305.2" "ENST00000488147.1"
[4] "ENST00000619216.1" "ENST00000473358.1" "ENST00000469289.1"</code></pre>
</div>
</div>
<p>The SummarizedExperiment object contains 205,870 rows and 2 columns. The rows correspond to transcript level data, indicated by the rownames being the Ensembl transcript ID.</p>
</section>
<section id="summarizedexperiment-object" class="level3">
<h3 class="anchored" data-anchor-id="summarizedexperiment-object">SummarizedExperiment object</h3>
<p>The components of a SummarizedExperiment object are diagrammed with the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>),<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>),<span class="at">bty=</span><span class="st">"n"</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">type=</span><span class="st">"n"</span>,<span class="at">xlab=</span><span class="st">""</span>,<span class="at">ylab=</span><span class="st">""</span>,<span class="at">xaxt=</span><span class="st">"n"</span>,<span class="at">yaxt=</span><span class="st">"n"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(<span class="dv">45</span>,<span class="dv">90</span>,<span class="dv">90</span>,<span class="dv">45</span>),<span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">5</span>,<span class="dv">70</span>,<span class="dv">70</span>),<span class="at">col=</span><span class="st">"pink"</span>,<span class="at">border=</span><span class="cn">NA</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(<span class="dv">45</span>,<span class="dv">90</span>,<span class="dv">90</span>,<span class="dv">45</span>),<span class="fu">c</span>(<span class="dv">68</span>,<span class="dv">68</span>,<span class="dv">70</span>,<span class="dv">70</span>),<span class="at">col=</span><span class="st">"pink3"</span>,<span class="at">border=</span><span class="cn">NA</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">67.5</span>,<span class="dv">40</span>,<span class="st">"assay(s)"</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">67.5</span>,<span class="dv">35</span>,<span class="st">'e.g. "counts", ...'</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">40</span>,<span class="dv">40</span>,<span class="dv">10</span>),<span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">5</span>,<span class="dv">70</span>,<span class="dv">70</span>),<span class="at">col=</span><span class="st">"skyblue"</span>,<span class="at">border=</span><span class="cn">NA</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">40</span>,<span class="dv">40</span>,<span class="dv">10</span>),<span class="fu">c</span>(<span class="dv">68</span>,<span class="dv">68</span>,<span class="dv">70</span>,<span class="dv">70</span>),<span class="at">col=</span><span class="st">"skyblue3"</span>,<span class="at">border=</span><span class="cn">NA</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">25</span>,<span class="dv">40</span>,<span class="st">"rowRanges"</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(<span class="dv">45</span>,<span class="dv">90</span>,<span class="dv">90</span>,<span class="dv">45</span>),<span class="fu">c</span>(<span class="dv">75</span>,<span class="dv">75</span>,<span class="dv">95</span>,<span class="dv">95</span>),<span class="at">col=</span><span class="st">"palegreen"</span>,<span class="at">border=</span><span class="cn">NA</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(<span class="dv">45</span>,<span class="dv">47</span>,<span class="dv">47</span>,<span class="dv">45</span>),<span class="fu">c</span>(<span class="dv">75</span>,<span class="dv">75</span>,<span class="dv">95</span>,<span class="dv">95</span>),<span class="at">col=</span><span class="st">"palegreen3"</span>,<span class="at">border=</span><span class="cn">NA</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">67.5</span>,<span class="dv">85</span>,<span class="st">"colData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The SummarizedExperiment object contains three component parts: <code>rowRanges</code>, <code>colData</code>, and <code>assay</code>. The <code>colData</code> component contains sample annotations, such as sample ID. The <code>assay</code> component contains the matrix of counts (e.g.&nbsp;“counts”, “abundance”, “length”). The <code>rowRanges</code> contains annotation for corresponding row in the <code>assay</code> part (e.g.&nbsp;seqnames, genomic coordinates, strand, tx_id).</p>
</section>
<section id="summarize-to-gene-level" class="level3">
<h3 class="anchored" data-anchor-id="summarize-to-gene-level">summarize to gene level</h3>
<p>Since we will be performing gene-level analysis, we convert the transcript level data to gene level data with <a href="https://www.bioconductor.org/packages/release/bioc/html/tximeta.html">tximeta</a> with the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>gse <span class="ot">&lt;-</span> <span class="fu">summarizeToGene</span>(se)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>loading existing TxDb created: 2026-04-11 18:49:24</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>obtaining transcript-to-gene mapping from database</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>loading existing gene ranges created: 2026-04-11 18:50:07</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>assignRanges='range': gene ranges assigned by total range of isoforms
  see details at: ?summarizeToGene,SummarizedExperiment-method</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>summarizing abundance</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>summarizing counts</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>summarizing length</code></pre>
</div>
</div>
<p>Examination of gse with <code>dim()</code> and <code>head(rownames())</code> shows that the number of rows and columns remains unchanged. The rownames have changed from the Ensembl transcript ID to Ensembl gene ID, indicating the <code>assay</code> contains gene level data instead of transcript level data now.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(gse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 58294     2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">rownames</span>(gse))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ENSG00000000003.14" "ENSG00000000005.5"  "ENSG00000000419.12"
[4] "ENSG00000000457.13" "ENSG00000000460.16" "ENSG00000000938.12"</code></pre>
</div>
</div>
</section>
<section id="gse-from-airway" class="level3">
<h3 class="anchored" data-anchor-id="gse-from-airway">gse from airway</h3>
<p>For demonstrative purposes, this workflow will use the <code>gse</code> provided by the <a href="https://www.bioconductor.org/packages/release/data/experiment/html/airway.html">airway</a> package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">##loadfullgse</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(gse)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>gse</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>class: RangedSummarizedExperiment 
dim: 58294 8 
metadata(6): tximetaInfo quantInfo ... txomeInfo txdbInfo
assays(3): counts abundance length
rownames(58294): ENSG00000000003.14 ENSG00000000005.5 ...
  ENSG00000285993.1 ENSG00000285994.1
rowData names(1): gene_id
colnames(8): SRR1039508 SRR1039509 ... SRR1039520 SRR1039521
colData names(3): names donor condition</code></pre>
</div>
</div>
<p>The full gse contains 58294 rowsand 8 columns. The rownames are gene_id and the colnames are SRR IDs. Data about the genes are contained in the <code>rowRanges</code> component, phenotypic data about the samples are contained in the <code>colData</code> component, and the count matrices are contained in the <code>assay</code> component.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## assaysgse</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">assayNames</span>(gse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "counts"    "abundance" "length"   </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">assay</span>(gse), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516
ENSG00000000003.14    708.164    467.962    900.992    424.368   1188.295
ENSG00000000005.5       0.000      0.000      0.000      0.000      0.000
ENSG00000000419.12    455.000    510.000    604.000    352.000    583.000
                   SRR1039517 SRR1039520 SRR1039521
ENSG00000000003.14   1090.668    805.929    599.337
ENSG00000000005.5       0.000      0.000      0.000
ENSG00000000419.12    773.999    409.999    499.000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">assay</span>(gse))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516 SRR1039517 SRR1039520 
  21100805   19298584   26145537   15688246   25268618   31891456   19683767 
SRR1039521 
  21813903 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="do">##rowrangesgse</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rowRanges</span>(gse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>GRanges object with 58294 ranges and 1 metadata column:
                     seqnames              ranges strand |            gene_id
                        &lt;Rle&gt;           &lt;IRanges&gt;  &lt;Rle&gt; |        &lt;character&gt;
  ENSG00000000003.14     chrX 100627109-100639991      - | ENSG00000000003.14
   ENSG00000000005.5     chrX 100584802-100599885      + |  ENSG00000000005.5
  ENSG00000000419.12    chr20   50934867-50958555      - | ENSG00000000419.12
  ENSG00000000457.13     chr1 169849631-169894267      - | ENSG00000000457.13
  ENSG00000000460.16     chr1 169662007-169854080      + | ENSG00000000460.16
                 ...      ...                 ...    ... .                ...
   ENSG00000285990.1    chr14   19244904-19269380      - |  ENSG00000285990.1
   ENSG00000285991.1     chr6 149817937-149896011      - |  ENSG00000285991.1
   ENSG00000285992.1     chr8   47129262-47132628      + |  ENSG00000285992.1
   ENSG00000285993.1    chr18   46409197-46410645      - |  ENSG00000285993.1
   ENSG00000285994.1    chr10   12563151-12567351      + |  ENSG00000285994.1
  -------
  seqinfo: 25 sequences (1 circular) from hg38 genome</code></pre>
</div>
</div>
<p><code>rowRanges</code> for <code>gse</code> contains the genomic range annotation data that includes the Ensembl gene ID, genomic coordinates, and strand.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="do">##lookseqinfo</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">seqinfo</span>(<span class="fu">rowRanges</span>(gse))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Seqinfo object with 25 sequences (1 circular) from hg38 genome:
  seqnames seqlengths isCircular genome
  chr1      248956422      FALSE   hg38
  chr2      242193529      FALSE   hg38
  chr3      198295559      FALSE   hg38
  chr4      190214555      FALSE   hg38
  chr5      181538259      FALSE   hg38
  ...             ...        ...    ...
  chr21      46709983      FALSE   hg38
  chr22      50818468      FALSE   hg38
  chrX      156040895      FALSE   hg38
  chrY       57227415      FALSE   hg38
  chrM          16569       TRUE   hg38</code></pre>
</div>
</div>
<p><code>seqinfo</code> for <code>rowRanges</code> contains metadata about the chromosome sequences used.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="do">##coldatagse</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colData</span>(gse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>DataFrame with 8 rows and 3 columns
                names    donor     condition
             &lt;factor&gt; &lt;factor&gt;      &lt;factor&gt;
SRR1039508 SRR1039508  N61311  Untreated    
SRR1039509 SRR1039509  N61311  Dexamethasone
SRR1039512 SRR1039512  N052611 Untreated    
SRR1039513 SRR1039513  N052611 Dexamethasone
SRR1039516 SRR1039516  N080611 Untreated    
SRR1039517 SRR1039517  N080611 Dexamethasone
SRR1039520 SRR1039520  N061011 Untreated    
SRR1039521 SRR1039521  N061011 Dexamethasone</code></pre>
</div>
</div>
<p>The <code>colData</code> for <code>gse</code> contains sample identifying information provided by the sample table from earlier.</p>
</section>
</section>
<section id="deseqdataset" class="level2">
<h2 class="anchored" data-anchor-id="deseqdataset">DESeqDataSet</h2>
<p>This analysis will use the <a href="https://www.bioconductor.org/packages/release/bioc/html/DESeq2.html">DESeq2</a> package for differential expression <span class="citation" data-cites="love_moderated_2014">(<a href="#ref-love_moderated_2014" role="doc-biblioref">Michael I. Love, Huber, and Anders 2014</a>)</span>. <a href="https://www.bioconductor.org/packages/release/bioc/html/DESeq2.html">DESeq2</a> uses the DESeqDataSet object that is built on top of the SummarizedExperiment object.</p>
<p>The donor and condition variables in <code>colData</code> can be examined directly with <code>$</code> subsetting of the SummarizedExperiment (or DESeqDataSet).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="do">##gsevars</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>gse<span class="sc">$</span>donor</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] N61311  N61311  N052611 N052611 N080611 N080611 N061011 N061011
Levels: N052611 N061011 N080611 N61311</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>gse<span class="sc">$</span>condition</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Untreated     Dexamethasone Untreated     Dexamethasone Untreated    
[6] Dexamethasone Untreated     Dexamethasone
Levels: Untreated Dexamethasone</code></pre>
</div>
</div>
<p>We rename the <code>colData</code> variables <code>donor</code> and <code>condition</code> to <code>cell</code> and <code>dex</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="do">##gsevarsrename</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>gse<span class="sc">$</span>cell <span class="ot">&lt;-</span> gse<span class="sc">$</span>donor </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>gse<span class="sc">$</span>dex <span class="ot">&lt;-</span> gse<span class="sc">$</span>condition</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>dex</code> is a factor with 2 levels. We rename the levels of <code>dex</code>; <code>untrt</code> replaces <code>Untreated</code> and <code>trt</code> replaces <code>Dexamethasone</code>. Using <a href="https://cran.rstudio.com/web/packages/magrittr/index.html">magrittr</a> <span class="citation" data-cites="bache_magrittr_2014">(<a href="#ref-bache_magrittr_2014" role="doc-biblioref">Bache and Wickham 2014</a>)</span>, the levels of <code>dex</code> are ordered properly with relevel so that <code>untrt</code> is the first level. (<code>dex</code> was already properly ordered, so this example shows how to relevel the factor if not already properly ordered)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="do">##renamelevels</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(gse<span class="sc">$</span>dex)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Untreated"     "Dexamethasone"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># when renaming levels, the order must be preserved!</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(gse<span class="sc">$</span>dex) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"untrt"</span>, <span class="st">"trt"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="do">##gsedex</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"magrittr"</span>) </span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>gse<span class="sc">$</span>dex <span class="sc">%&lt;&gt;%</span> <span class="fu">relevel</span>(<span class="st">"untrt"</span>)</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>gse<span class="sc">$</span>dex</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] untrt trt   untrt trt   untrt trt   untrt trt  
Levels: untrt trt</code></pre>
</div>
</div>
<p>We can view how many millions of fragments per sample could be mapped:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="do">##countreads</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>( <span class="fu">colSums</span>(<span class="fu">assay</span>(gse)) <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">1</span> )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516 SRR1039517 SRR1039520 
      21.1       19.3       26.1       15.7       25.3       31.9       19.7 
SRR1039521 
      21.8 </code></pre>
</div>
</div>
<p>The DESeqDataSet is created with the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="do">##loaddeseq2</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"DESeq2"</span>)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="do">##makedds</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>dds <span class="ot">&lt;-</span> <span class="fu">DESeqDataSet</span>(gse, <span class="at">design =</span> <span class="sc">~</span> cell <span class="sc">+</span> dex)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>using counts and average transcript lengths from tximeta</code></pre>
</div>
</div>
<p>We specify the fixed-effects experimental design within the <code>DESeqDataSet()</code> call by using R’s formula notation as an argument (i.e.&nbsp;~ group + treatment + group:treatment). For our analysis, we are testing for the effect of <code>dex</code> (treatment) while controlling for <code>cell</code> (donor). Our supplied design is thus <code>design = ~ cell + dex</code>.</p>
</section>
<section id="exploratory-analysis-and-visualization" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-analysis-and-visualization">Exploratory analysis and visualization</h2>
<section id="prefiltering" class="level3">
<h3 class="anchored" data-anchor-id="prefiltering">Prefiltering</h3>
<p>We remove rows that contain no or nearly no genomic expression with the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Prefiltering</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(dds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 58294</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>smallestGroupSize <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>keep <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(<span class="fu">counts</span>(dds) <span class="sc">&gt;=</span> <span class="dv">10</span>) <span class="sc">&gt;=</span> smallestGroupSize</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>dds <span class="ot">&lt;-</span> dds[keep,]</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(dds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16637</code></pre>
</div>
</div>
<p>The prefiltering filters out rows (genes) that contain less than 10 fragments for their respective gene in fewer samples than the smallest group size (4 in this case). Prefiltering has reduced the number of rows in the <code>gse</code> from 58294 to 16637. Additional weighting/filtering to improve power is applied at a later step.</p>
</section>
<section id="variance-stabilizing-transformation-and-the-rlog" class="level3">
<h3 class="anchored" data-anchor-id="variance-stabilizing-transformation-and-the-rlog">Variance stabilizing transformation and the rlog</h3>
<p>We improve the homoscedasticity of the rna-seq data by applying the variance stabilizing transformation (<code>vst</code>) <span class="citation" data-cites="anders_differential_2010">(<a href="#ref-anders_differential_2010" role="doc-biblioref">Anders and Huber 2010</a>)</span> or regularized logarithm transformation (<code>rlog</code>) <span class="citation" data-cites="love_moderated_2014">(<a href="#ref-love_moderated_2014" role="doc-biblioref">Michael I. Love, Huber, and Anders 2014</a>)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="do">##vst</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>vsd <span class="ot">&lt;-</span> <span class="fu">vst</span>(dds, <span class="at">blind =</span> <span class="cn">FALSE</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">assay</span>(vsd), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516
ENSG00000000003.14  10.082167   9.828058  10.152774   9.970690  10.410407
ENSG00000000419.12   9.663489   9.900634   9.779942   9.775148   9.740478
ENSG00000000457.13   9.417376   9.280001   9.333639   9.430438   9.250501
                   SRR1039517 SRR1039520 SRR1039521
ENSG00000000003.14  10.171994  10.300682   9.976235
ENSG00000000419.12   9.848458   9.659469   9.817695
ENSG00000000457.13   9.363013   9.450889   9.444291</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colData</span>(vsd)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>DataFrame with 8 rows and 5 columns
                names    donor     condition     cell      dex
             &lt;factor&gt; &lt;factor&gt;      &lt;factor&gt; &lt;factor&gt; &lt;factor&gt;
SRR1039508 SRR1039508  N61311  Untreated      N61311     untrt
SRR1039509 SRR1039509  N61311  Dexamethasone  N61311     trt  
SRR1039512 SRR1039512  N052611 Untreated      N052611    untrt
SRR1039513 SRR1039513  N052611 Dexamethasone  N052611    trt  
SRR1039516 SRR1039516  N080611 Untreated      N080611    untrt
SRR1039517 SRR1039517  N080611 Dexamethasone  N080611    trt  
SRR1039520 SRR1039520  N061011 Untreated      N061011    untrt
SRR1039521 SRR1039521  N061011 Dexamethasone  N061011    trt  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="do">##rlog</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>rld <span class="ot">&lt;-</span> <span class="fu">rlog</span>(dds, <span class="at">blind =</span> <span class="cn">FALSE</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">assay</span>(rld), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516
ENSG00000000003.14   9.479269   9.172988   9.561792   9.347935   9.853759
ENSG00000000419.12   8.856681   9.150490   9.003390   8.997381   8.954032
ENSG00000000457.13   8.352320   8.165586   8.239148   8.368679   8.122726
                   SRR1039517 SRR1039520 SRR1039521
ENSG00000000003.14   9.584201   9.730416   9.353458
ENSG00000000419.12   9.088130   8.851863   9.049900
ENSG00000000457.13   8.279323   8.396402   8.387635</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co">#transformplot, fig.width = 6, fig.height = 2.5</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>dds <span class="ot">&lt;-</span> <span class="fu">estimateSizeFactors</span>(dds)</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_data_frame</span>(<span class="fu">log2</span>(<span class="fu">counts</span>(dds, <span class="at">normalized=</span><span class="cn">TRUE</span>)[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]<span class="sc">+</span><span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>         <span class="fu">mutate</span>(<span class="at">transformation =</span> <span class="st">"log2(x + 1)"</span>),</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_data_frame</span>(<span class="fu">assay</span>(vsd)[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">transformation =</span> <span class="st">"vst"</span>),</span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_data_frame</span>(<span class="fu">assay</span>(rld)[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">transformation =</span> <span class="st">"rlog"</span>))</span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df)[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>)  </span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>lvls <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"log2(x + 1)"</span>, <span class="st">"vst"</span>, <span class="st">"rlog"</span>)</span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>transformation <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>transformation, <span class="at">levels=</span>lvls)</span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span> <span class="fu">geom_hex</span>(<span class="at">bins =</span> <span class="dv">80</span>) <span class="sc">+</span></span>
<span id="cb70-19"><a href="#cb70-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_fixed</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>( . <span class="sc">~</span> transformation)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p><code>VST</code> and <code>rlog</code> both improve the homogeneity of variance compared to a traditional log transformation approach of taking the logarithm of the normalized count values and adding a pseudo-count, e.g.&nbsp;log2(x + 1). <code>VST</code> is recommended for medium to large data sets, while <code>rlog</code> works well on small data sets and when a wide range of sequencing depth across samples. <code>VST</code> and <code>rlog</code> transformations are not intended for differential testing. <code>VST</code> and <code>rlog</code> return a DESeqTransform object. Transformed values are stored in the <code>assay</code> component, but are no longer counts.</p>
</section>
<section id="sample-distances" class="level3">
<h3 class="anchored" data-anchor-id="sample-distances">Sample distances</h3>
<p>To assess similarity between samples, the Euclidean distance between samples is calculated using the <code>VST</code> data. The R function <code>dist()</code> expects the samples to be rows and dimensions to be columns. The <code>assay</code> componment with <code>VST</code> data (<code>VSD</code>) needs to be transposed prior to being provided to the <code>dist()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>sampleDists <span class="ot">&lt;-</span> <span class="fu">dist</span>(<span class="fu">t</span>(<span class="fu">assay</span>(vsd)))</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>sampleDists</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516 SRR1039517
SRR1039509   37.77776                                                       
SRR1039512   30.25948   43.38127                                            
SRR1039513   49.66501   34.84097   40.18573                                 
SRR1039516   33.62914   46.11028   32.89674   50.61885                      
SRR1039517   50.13559   39.95782   45.59332   38.73688   38.49412           
SRR1039520   29.92878   45.27463   27.72834   46.25456   34.97574   48.96752
SRR1039521   50.08387   35.35988   45.51074   28.48458   51.19216   39.62934
           SRR1039520
SRR1039509           
SRR1039512           
SRR1039513           
SRR1039516           
SRR1039517           
SRR1039520           
SRR1039521   41.45015</code></pre>
</div>
</div>
</section>
<section id="heatmap-pheatmap-sample-distances-using-variance-stabilizing-transformation" class="level3">
<h3 class="anchored" data-anchor-id="heatmap-pheatmap-sample-distances-using-variance-stabilizing-transformation">Heatmap (Pheatmap) sample distances using variance stabilizing transformation</h3>
<p>The distances can be visualized using a heat map produced by the <a href="https://cran.r-project.org/web/packages/pheatmap/index.html">pheatmap</a> package <span class="citation" data-cites="kolde_pheatmap_2010">(<a href="#ref-kolde_pheatmap_2010" role="doc-biblioref">Kolde 2010</a>)</span>.</p>
<p>The <code>sampleDists</code> is provided to the <code>clustering_distance</code> argument of the <code>pheatmap()</code> function. The <code>rownames</code> are changed for convenience and a blue color palette is used for the heat map.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pheatmap)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="do">##distheatmap</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>sampleDistMatrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>( sampleDists )</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(sampleDistMatrix) <span class="ot">&lt;-</span> <span class="fu">paste</span>( vsd<span class="sc">$</span>dex, vsd<span class="sc">$</span>cell, <span class="at">sep =</span> <span class="st">" - "</span> )</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(sampleDistMatrix) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">colorRampPalette</span>( <span class="fu">rev</span>(<span class="fu">brewer.pal</span>(<span class="dv">9</span>, <span class="st">"Blues"</span>)) )(<span class="dv">255</span>)</span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a><span class="fu">pheatmap</span>(sampleDistMatrix,</span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">clustering_distance_rows =</span> sampleDists,</span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">clustering_distance_cols =</span> sampleDists,</span>
<span id="cb73-12"><a href="#cb73-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> colors)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The heat map of sample to sample distances using <code>VST</code> values indicates that samples with the same treatment condition are more similar (less distance) than samples from different treatment groups.</p>
</section>
<section id="heat-map-sample-distances-using-poisson-distance" class="level3">
<h3 class="anchored" data-anchor-id="heat-map-sample-distances-using-poisson-distance">Heat map sample distances using Poisson distance</h3>
<p>Sample to sample distances using the Poisson distance can be represented in a heat map using the <a href="https://cran.r-project.org/web/packages/PoiClaClu/index.html">PoiClaClu</a> package <span class="citation" data-cites="daniela_witten_poiclaclu_2011">(<a href="#ref-daniela_witten_poiclaclu_2011" role="doc-biblioref">Daniela Witten 2011</a>)</span>. The <code>PoissonDistance()</code> function uses original count matrix values and requires the samples to be provided as rows. The <code>dds</code> counts need to be transposed prior to being provided.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"PoiClaClu"</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="co">#transpose dds sample columns to sample rows (original count matrix, not normalized, use dds not vsd or rld)</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>poisd <span class="ot">&lt;-</span> <span class="fu">PoissonDistance</span>(<span class="fu">t</span>(<span class="fu">counts</span>(dds)))</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a><span class="co">#plot heatmap</span></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>samplePoisDistMatrix <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>( poisd<span class="sc">$</span>dd )</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(samplePoisDistMatrix) <span class="ot">&lt;-</span> <span class="fu">paste</span>( dds<span class="sc">$</span>dex, dds<span class="sc">$</span>cell, <span class="at">sep=</span><span class="st">" - "</span> )</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(samplePoisDistMatrix) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a><span class="fu">pheatmap</span>(samplePoisDistMatrix,</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">clustering_distance_rows =</span> poisd<span class="sc">$</span>dd,</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">clustering_distance_cols =</span> poisd<span class="sc">$</span>dd,</span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> colors)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="pca-plot-vst-data" class="level3">
<h3 class="anchored" data-anchor-id="pca-plot-vst-data">PCA plot (VST data)</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot PCA</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotPCA</span>(vsd, <span class="at">intgroup =</span> <span class="fu">c</span>(<span class="st">"dex"</span>, <span class="st">"cell"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>using ntop=500 top features by variance</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#principal component loadings</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>pcaData <span class="ot">&lt;-</span> <span class="fu">plotPCA</span>(vsd, <span class="at">intgroup =</span> <span class="fu">c</span>( <span class="st">"dex"</span>, <span class="st">"cell"</span>), <span class="at">returnData =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>using ntop=500 top features by variance</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>pcaData</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  PC1       PC2         group       name      names   donor
SRR1039508 -14.427794 -3.057906  untrt:N61311 SRR1039508 SRR1039508  N61311
SRR1039509   8.144808 -1.422929    trt:N61311 SRR1039509 SRR1039509  N61311
SRR1039512  -9.476223 -4.414224 untrt:N052611 SRR1039512 SRR1039512 N052611
SRR1039513  14.628644 -4.290437   trt:N052611 SRR1039513 SRR1039513 N052611
SRR1039516 -12.425251 11.397272 untrt:N080611 SRR1039516 SRR1039516 N080611
SRR1039517   9.475669 15.097249   trt:N080611 SRR1039517 SRR1039517 N080611
SRR1039520 -10.965862 -7.197057 untrt:N061011 SRR1039520 SRR1039520 N061011
SRR1039521  15.046009 -6.111969   trt:N061011 SRR1039521 SRR1039521 N061011
               condition    cell   dex
SRR1039508     Untreated  N61311 untrt
SRR1039509 Dexamethasone  N61311   trt
SRR1039512     Untreated N052611 untrt
SRR1039513 Dexamethasone N052611   trt
SRR1039516     Untreated N080611 untrt
SRR1039517 Dexamethasone N080611   trt
SRR1039520     Untreated N061011 untrt
SRR1039521 Dexamethasone N061011   trt</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>percentVar <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">attr</span>(pcaData, <span class="st">"percentVar"</span>))</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="co">#use ggplot to construct PCA plot after returning loadings</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pcaData, <span class="fu">aes</span>(<span class="at">x =</span> PC1, <span class="at">y =</span> PC2, <span class="at">color =</span> dex, <span class="at">shape =</span> cell)) <span class="sc">+</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="fu">paste0</span>(<span class="st">"PC1: "</span>, percentVar[<span class="dv">1</span>], <span class="st">"% variance"</span>)) <span class="sc">+</span></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="fu">paste0</span>(<span class="st">"PC2: "</span>, percentVar[<span class="dv">2</span>], <span class="st">"% variance"</span>)) <span class="sc">+</span></span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_fixed</span>() <span class="sc">+</span></span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"PCA with VST data"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The PCA plots indicate treatment condition as the greatest source of variance. PC1 accounts for 52% of the explained variance and clearly separates the samples by treatment condition. PC2 accounts for 22% of the explained variance, with a clear separation of samples by donor on PC2. Examining the principal component loadings, the samples with <code>trt</code> treatment condition (<code>dex</code>) clearly show their presence contributing to PC1 due to the positive loadings. The <code>untrt</code> samples have negative loadings of similar magnitude to the positive loadings of <code>trt</code> for PC1, clearly showing their absence contributes to PC1. Interestingly, some donors <code>trt</code> loadings have greater magnitude contributing to PC1, while some donors <code>untrt</code> samples have negative loadings of greater magnitude contributing to PC1 than their <code>trt</code> paired sample.</p>
</section>
<section id="generalized-pca-plot" class="level3">
<h3 class="anchored" data-anchor-id="generalized-pca-plot">Generalized PCA plot</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmpca)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>gpca <span class="ot">&lt;-</span> <span class="fu">glmpca</span>(<span class="fu">counts</span>(dds), <span class="at">L=</span><span class="dv">2</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>gpca.dat <span class="ot">&lt;-</span> gpca<span class="sc">$</span>factors</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>gpca.dat<span class="sc">$</span>dex <span class="ot">&lt;-</span> dds<span class="sc">$</span>dex</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>gpca.dat<span class="sc">$</span>cell <span class="ot">&lt;-</span> dds<span class="sc">$</span>cell</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gpca.dat, <span class="fu">aes</span>(<span class="at">x =</span> dim1, <span class="at">y =</span> dim2, <span class="at">color =</span> dex, <span class="at">shape =</span> cell)) <span class="sc">+</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span><span class="dv">3</span>) <span class="sc">+</span> <span class="fu">coord_fixed</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"glmpca - Generalized PCA"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="mds-plot" class="level3">
<h3 class="anchored" data-anchor-id="mds-plot">MDS plot</h3>
<p>Multidimensional scaling (MDS) requires a matrix of distances instead of matrix of counts.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co">#multidimensional scaling (MDS) function in base R. </span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="co">#This is useful when we don’t have a matrix of data, but only a matrix of distances</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="co">#MDS plot using VST data</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>mds <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">colData</span>(vsd))  <span class="sc">%&gt;%</span></span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>         <span class="fu">cbind</span>(<span class="fu">cmdscale</span>(sampleDistMatrix))</span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mds, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">1</span><span class="st">`</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">2</span><span class="st">`</span>, <span class="at">color =</span> dex, <span class="at">shape =</span> cell)) <span class="sc">+</span></span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="fu">coord_fixed</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"MDS with VST data"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>MDS plot using VST data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># MDS with PoissonDistances</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>mdsPois <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">colData</span>(dds)) <span class="sc">%&gt;%</span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">cbind</span>(<span class="fu">cmdscale</span>(samplePoisDistMatrix))</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mdsPois, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">1</span><span class="st">`</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">2</span><span class="st">`</span>, <span class="at">color =</span> dex, <span class="at">shape =</span> cell)) <span class="sc">+</span></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="fu">coord_fixed</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"MDS with PoissonDistances"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>MDS plot using PoissonDistances. MDS visualization using Poisson distances shows similar clustering patterns as the <code>VSD</code>, confirming consistency of results across distance metrics.</p>
</section>
</section>
<section id="differential-expression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="differential-expression-analysis">Differential expression analysis</h2>
<p>DESeq2 function tests for differential expression using negative binomial generalized linear models informed by estimations of dispersion and estimations of size factors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load dds into DESeq</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>dds <span class="ot">&lt;-</span> <span class="fu">DESeq</span>(dds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>using pre-existing normalization factors</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>estimating dispersions</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>gene-wise dispersion estimates</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>mean-dispersion relationship</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>final dispersion estimates</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>fitting model and testing</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">#building results table</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">results</span>(dds)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>res</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>log2 fold change (MLE): dex trt vs untrt 
Wald test p-value: dex trt vs untrt 
DataFrame with 16637 rows and 6 columns
                    baseMean log2FoldChange     lfcSE      stat      pvalue
                   &lt;numeric&gt;      &lt;numeric&gt; &lt;numeric&gt; &lt;numeric&gt;   &lt;numeric&gt;
ENSG00000000003.14  740.1093      -0.365327 0.1073385 -3.403501 6.65282e-04
ENSG00000000419.12  511.6990       0.202232 0.1278579  1.581694 1.13720e-01
ENSG00000000457.13  314.1680       0.033792 0.1552106  0.217717 8.27650e-01
ENSG00000000460.16   79.7988      -0.120633 0.3055270 -0.394836 6.92964e-01
ENSG00000000971.15 5715.3064       0.442982 0.0904089  4.899766 9.59508e-07
...                      ...            ...       ...       ...         ...
ENSG00000285953.1    29.5747      -1.920562  0.649661 -2.956253  0.00311401
ENSG00000285967.1   181.1650      -0.325885  0.179340 -1.817132  0.06919688
ENSG00000285976.1   875.4424       0.262132  0.142980  1.833351  0.06675037
ENSG00000285979.1    38.3502       0.338383  0.348445  0.971124  0.33148631
ENSG00000285991.1    11.2772      -0.115472  0.723139 -0.159681  0.87313221
                          padj
                     &lt;numeric&gt;
ENSG00000000003.14 4.63552e-03
ENSG00000000419.12 2.88125e-01
ENSG00000000457.13 9.21718e-01
ENSG00000000460.16 8.48743e-01
ENSG00000000971.15 1.36387e-05
...                        ...
ENSG00000285953.1    0.0171889
ENSG00000285967.1    0.2019448
ENSG00000285976.1    0.1965808
ENSG00000285979.1    0.5713913
ENSG00000285991.1           NA</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co">#alternative code</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="co">#res &lt;- results(dds,        contrast=c("dex","trt","untrt"))</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
out of 16637 with nonzero total read count
adjusted p-value &lt; 0.1
LFC &gt; 0 (up)       : 2362, 14%
LFC &lt; 0 (down)     : 2019, 12%
outliers [1]       : 0, 0%
low counts [2]     : 646, 3.9%
(mean count &lt; 12)
[1] see 'cooksCutoff' argument of ?results
[2] see 'independentFiltering' argument of ?results</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co">#if using lower False Discovery Rate threshold, supply new alpha to results function</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="co">#res.05 &lt;- results(dds, alpha = 0.05)</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="co">#table(res.05$padj &lt; 0.05)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>res$log2FoldChange</code> is the effect size estimate, informing us how the <code>trt</code> condition may have changed genomic expression. <code>lfcSE</code> is the standard error estimate for the change in effect size estimate (<code>log2FoldChange</code>) ### Multiple testing</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co">#num of sig and non sig log fold change</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(res<span class="sc">$</span>pvalue <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5069</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(res<span class="sc">$</span>pvalue))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16637</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co">#num of sig log fold change after threshold adjustment</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(res<span class="sc">$</span>padj <span class="sc">&lt;</span> <span class="fl">0.1</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4381</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co">#subset and sort log2 change estimate of strongest down and up regulation</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>resSig <span class="ot">&lt;-</span> <span class="fu">subset</span>(res, padj <span class="sc">&lt;</span> <span class="fl">0.1</span>)</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(resSig[ <span class="fu">order</span>(resSig<span class="sc">$</span>log2FoldChange), ])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>log2 fold change (MLE): dex trt vs untrt 
Wald test p-value: dex trt vs untrt 
DataFrame with 6 rows and 6 columns
                    baseMean log2FoldChange     lfcSE      stat      pvalue
                   &lt;numeric&gt;      &lt;numeric&gt; &lt;numeric&gt; &lt;numeric&gt;   &lt;numeric&gt;
ENSG00000216490.3    42.3457       -5.72709  1.474282  -3.88466 1.02473e-04
ENSG00000267339.5    30.5903       -5.39692  0.754323  -7.15465 8.38861e-13
ENSG00000146006.7    61.6555       -4.48259  0.643341  -6.96767 3.22240e-12
ENSG00000155897.9    23.9892       -3.87698  0.809195  -4.79115 1.65824e-06
ENSG00000213240.8    12.1002       -3.79153  1.221385  -3.10429 1.90737e-03
ENSG00000162692.11  505.5613       -3.67636  0.201427 -18.25164 2.00779e-74
                          padj
                     &lt;numeric&gt;
ENSG00000216490.3  9.14426e-04
ENSG00000267339.5  2.76013e-11
ENSG00000146006.7  9.83385e-11
ENSG00000155897.9  2.25676e-05
ENSG00000213240.8  1.14064e-02
ENSG00000162692.11 2.00666e-71</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(resSig[ <span class="fu">order</span>(resSig<span class="sc">$</span>log2FoldChange, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>log2 fold change (MLE): dex trt vs untrt 
Wald test p-value: dex trt vs untrt 
DataFrame with 6 rows and 6 columns
                    baseMean log2FoldChange     lfcSE      stat      pvalue
                   &lt;numeric&gt;      &lt;numeric&gt; &lt;numeric&gt; &lt;numeric&gt;   &lt;numeric&gt;
ENSG00000254692.1    62.1517       10.20327  3.377058   3.02135 2.51651e-03
ENSG00000179593.15   66.9666        9.50105  1.070620   8.87435 7.03444e-19
ENSG00000224712.12   35.5516        7.16466  2.164701   3.30977 9.33725e-04
ENSG00000109906.13  437.5025        6.37252  0.309988  20.55731 6.62052e-94
ENSG00000257663.1    24.3615        6.34094  2.094868   3.02689 2.47081e-03
ENSG00000250978.5    45.6682        5.91333  0.710469   8.32314 8.56661e-17
                          padj
                     &lt;numeric&gt;
ENSG00000254692.1  1.44165e-02
ENSG00000179593.15 4.22886e-17
ENSG00000224712.12 6.18525e-03
ENSG00000109906.13 1.17632e-90
ENSG00000257663.1  1.42176e-02
ENSG00000250978.5  4.32141e-15</code></pre>
</div>
</div>
</section>
<section id="plotting-results" class="level2">
<h2 class="anchored" data-anchor-id="plotting-results">Plotting results</h2>
<section id="counts-plot" class="level3">
<h3 class="anchored" data-anchor-id="counts-plot">Counts plot</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>topGene <span class="ot">&lt;-</span> <span class="fu">rownames</span>(res)[<span class="fu">which.min</span>(res<span class="sc">$</span>padj)]</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotCounts</span>(dds, <span class="at">gene =</span> topGene, <span class="at">intgroup=</span><span class="fu">c</span>(<span class="st">"dex"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="do">##ggplotcountsjitter</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggbeeswarm)</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>geneCounts <span class="ot">&lt;-</span> <span class="fu">plotCounts</span>(dds, <span class="at">gene =</span> topGene, <span class="at">intgroup =</span> <span class="fu">c</span>(<span class="st">"dex"</span>,<span class="st">"cell"</span>),</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">returnData =</span> <span class="cn">TRUE</span>)</span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(geneCounts, <span class="fu">aes</span>(<span class="at">x =</span> dex, <span class="at">y =</span> count, <span class="at">color =</span> cell)) <span class="sc">+</span></span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span>  <span class="fu">geom_beeswarm</span>(<span class="at">cex =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="do">##ggplotcountsgroup</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(geneCounts, <span class="fu">aes</span>(<span class="at">x =</span> dex, <span class="at">y =</span> count, <span class="at">color =</span> cell, <span class="at">group =</span> cell)) <span class="sc">+</span></span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> <span class="fu">geom_line</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="ma-plot" class="level3">
<h3 class="anchored" data-anchor-id="ma-plot">MA-plot</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="do">##plotma</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(apeglm)</span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="fu">resultsNames</span>(dds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Intercept"               "cell_N061011_vs_N052611"
[3] "cell_N080611_vs_N052611" "cell_N61311_vs_N052611" 
[5] "dex_trt_vs_untrt"       </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">lfcShrink</span>(dds, <span class="at">coef=</span><span class="st">"dex_trt_vs_untrt"</span>, <span class="at">type=</span><span class="st">"apeglm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>using 'apeglm' for LFC shrinkage. If used in published research, please cite:
    Zhu, A., Ibrahim, J.G., Love, M.I. (2018) Heavy-tailed prior distributions for
    sequence count data: removing the noise and preserving large differences.
    Bioinformatics. https://doi.org/10.1093/bioinformatics/bty895</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotMA</span>(res, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="do">##plotmaNoShr</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>res.noshr <span class="ot">&lt;-</span> <span class="fu">results</span>(dds, <span class="at">name=</span><span class="st">"dex_trt_vs_untrt"</span>)</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plotMA</span>(res.noshr, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="do">##plotmalabel-</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotMA</span>(res, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>))</span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>topGene <span class="ot">&lt;-</span> <span class="fu">rownames</span>(res)[<span class="fu">which.min</span>(res<span class="sc">$</span>padj)]</span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(res[topGene, ], {</span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(baseMean, log2FoldChange, <span class="at">col=</span><span class="st">"dodgerblue"</span>, <span class="at">cex=</span><span class="dv">2</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">text</span>(baseMean, log2FoldChange, topGene, <span class="at">pos=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"dodgerblue"</span>)</span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="do">##histpvalue2</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(res<span class="sc">$</span>pvalue[res<span class="sc">$</span>baseMean <span class="sc">&gt;</span> <span class="dv">1</span>], <span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">20</span><span class="sc">/</span><span class="dv">20</span>,</span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"grey50"</span>, <span class="at">border =</span> <span class="st">"white"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="gene-clustering" class="level3">
<h3 class="anchored" data-anchor-id="gene-clustering">Gene clustering</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(genefilter)</span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>topVarGenes <span class="ot">&lt;-</span> <span class="fu">head</span>(<span class="fu">order</span>(<span class="fu">rowVars</span>(<span class="fu">assay</span>(vsd)), <span class="at">decreasing =</span> <span class="cn">TRUE</span>), <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="do">##genescluster</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>mat  <span class="ot">&lt;-</span> <span class="fu">assay</span>(vsd)[ topVarGenes, ]</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>mat  <span class="ot">&lt;-</span> mat <span class="sc">-</span> <span class="fu">rowMeans</span>(mat)</span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a>anno <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">colData</span>(vsd)[, <span class="fu">c</span>(<span class="st">"cell"</span>,<span class="st">"dex"</span>)])</span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pheatmap</span>(mat, <span class="at">annotation_col =</span> anno)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="annotating-and-exporting-results" class="level2">
<h2 class="anchored" data-anchor-id="annotating-and-exporting-results">Annotating and exporting results</h2>
<p>Thus far our gene level data corrosponds to Ensembl gene IDs. Utilizing Bioconductor’s annotation pacakges, alternative gene names can be mapped to potentially improve interpretation. Load the <a href="https://bioconductor.org/packages/3.20/bioc/html/AnnotationDbi.html">AnnotationDbi</a> and <a href="https://bioconductor.org/packages/3.20/data/annotation/html/org.Hs.eg.db.html">org.Hs.eg.db</a> package <span class="citation" data-cites="herve_pages_annotationdbi_2017 carlson_orghsegdb_2017">(<a href="#ref-herve_pages_annotationdbi_2017" role="doc-biblioref">Hervé Pagès 2017</a>; <a href="#ref-carlson_orghsegdb_2017" role="doc-biblioref">Carlson 2017</a>)</span>.</p>
<p>The <a href="https://bioconductor.org/packages/3.20/data/annotation/html/org.Hs.eg.db.html">org.Hs.eg.db</a> package name can be deciphered as organism annotation package (“org”) for Homo sapiens (“Hs”), organized as an AnnotationDbi database (“db”), using Entrez Gene IDs (“eg”) as primary key. The following code produces a list of available key types:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AnnotationDbi)</span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(org.Hs.eg.db)</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a><span class="fu">columns</span>(org.Hs.eg.db)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ACCNUM"       "ALIAS"        "ENSEMBL"      "ENSEMBLPROT"  "ENSEMBLTRANS"
 [6] "ENTREZID"     "ENZYME"       "EVIDENCE"     "EVIDENCEALL"  "GENENAME"    
[11] "GENETYPE"     "GO"           "GOALL"        "IPI"          "MAP"         
[16] "OMIM"         "ONTOLOGY"     "ONTOLOGYALL"  "PATH"         "PFAM"        
[21] "PMID"         "PROSITE"      "REFSEQ"       "SYMBOL"       "UCSCKG"      
[26] "UNIPROT"     </code></pre>
</div>
</div>
<p>Use <code>mapIds()</code> function to add individual columns to a results table. The results’ table uses rownames as a key, specifying <code>keytype=ENSEMBL</code>. <code>mapsIds()</code> uses the <code>column</code> argument to identify which information we want. The <code>multiVals</code> argument handles potential multiple values for a single input. The following code adds a column for gene symbol and a column for Entrez ID.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>ens.str <span class="ot">&lt;-</span> <span class="fu">substr</span>(<span class="fu">rownames</span>(res), <span class="dv">1</span>, <span class="dv">15</span>)</span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>res<span class="sc">$</span>symbol <span class="ot">&lt;-</span> <span class="fu">mapIds</span>(org.Hs.eg.db,</span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">keys=</span>ens.str,</span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">column=</span><span class="st">"SYMBOL"</span>,</span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">keytype=</span><span class="st">"ENSEMBL"</span>,</span>
<span id="cb122-6"><a href="#cb122-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">multiVals=</span><span class="st">"first"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>'select()' returned 1:many mapping between keys and columns</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>res<span class="sc">$</span>entrez <span class="ot">&lt;-</span> <span class="fu">mapIds</span>(org.Hs.eg.db,</span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">keys=</span>ens.str,</span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">column=</span><span class="st">"ENTREZID"</span>,</span>
<span id="cb124-4"><a href="#cb124-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">keytype=</span><span class="st">"ENSEMBL"</span>,</span>
<span id="cb124-5"><a href="#cb124-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">multiVals=</span><span class="st">"first"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>'select()' returned 1:many mapping between keys and columns</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>resOrdered <span class="ot">&lt;-</span> res[<span class="fu">order</span>(res<span class="sc">$</span>pvalue),]</span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(resOrdered)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>log2 fold change (MAP): dex trt vs untrt 
Wald test p-value: dex trt vs untrt 
DataFrame with 6 rows and 7 columns
                    baseMean log2FoldChange     lfcSE       pvalue         padj
                   &lt;numeric&gt;      &lt;numeric&gt; &lt;numeric&gt;    &lt;numeric&gt;    &lt;numeric&gt;
ENSG00000189221.9   2371.265        3.38410  0.136340 2.47518e-138 3.95806e-134
ENSG00000120129.5   3417.255        2.95871  0.121485 3.44226e-133 2.75226e-129
ENSG00000101347.9  14106.720        3.73919  0.157542 1.66892e-127 8.89591e-124
ENSG00000152583.12   973.479        4.48318  0.199191 2.26145e-115 9.04071e-112
ENSG00000196136.17  2708.309        3.22904  0.144707 1.23286e-112 3.94293e-109
ENSG00000211445.11 12502.886        3.75413  0.170078 2.52549e-111 6.73085e-108
                        symbol      entrez
                   &lt;character&gt; &lt;character&gt;
ENSG00000189221.9         MAOA        4128
ENSG00000120129.5        DUSP1        1843
ENSG00000101347.9       SAMHD1       25939
ENSG00000152583.12     SPARCL1        8404
ENSG00000196136.17    SERPINA3          12
ENSG00000211445.11        GPX3        2878</code></pre>
</div>
</div>
<section id="exporting-results" class="level3">
<h3 class="anchored" data-anchor-id="exporting-results">Exporting results</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>resOrderedDF <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(resOrdered)[<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, ]</span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(resOrderedDF, <span class="at">file =</span> <span class="st">"results.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="plotting-fold-changes-in-genomic-space" class="level3">
<h3 class="anchored" data-anchor-id="plotting-fold-changes-in-genomic-space">Plotting fold changes in genomic space</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>resGR <span class="ot">&lt;-</span> <span class="fu">lfcShrink</span>(dds, <span class="at">coef=</span><span class="st">"dex_trt_vs_untrt"</span>, <span class="at">type=</span><span class="st">"apeglm"</span>, <span class="at">format=</span><span class="st">"GRanges"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>using 'apeglm' for LFC shrinkage. If used in published research, please cite:
    Zhu, A., Ibrahim, J.G., Love, M.I. (2018) Heavy-tailed prior distributions for
    sequence count data: removing the noise and preserving large differences.
    Bioinformatics. https://doi.org/10.1093/bioinformatics/bty895</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>resGR</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>GRanges object with 16637 ranges and 5 metadata columns:
                     seqnames              ranges strand |  baseMean
                        &lt;Rle&gt;           &lt;IRanges&gt;  &lt;Rle&gt; | &lt;numeric&gt;
  ENSG00000000003.14     chrX 100627109-100639991      - |  740.1093
  ENSG00000000419.12    chr20   50934867-50958555      - |  511.6990
  ENSG00000000457.13     chr1 169849631-169894267      - |  314.1680
  ENSG00000000460.16     chr1 169662007-169854080      + |   79.7988
  ENSG00000000971.15     chr1 196651878-196747504      + | 5715.3064
                 ...      ...                 ...    ... .       ...
   ENSG00000285953.1     chr7   92131774-92245924      - |   29.5747
   ENSG00000285967.1     chr5   36864425-36876700      - |  181.1650
   ENSG00000285976.1     chr6   63572012-63583587      + |  875.4424
   ENSG00000285979.1    chr16   57177349-57181390      + |   38.3502
   ENSG00000285991.1     chr6 149817937-149896011      - |   11.2772
                     log2FoldChange     lfcSE      pvalue        padj
                          &lt;numeric&gt; &lt;numeric&gt;   &lt;numeric&gt;   &lt;numeric&gt;
  ENSG00000000003.14     -0.3401220 0.1063304 6.65282e-04 4.63552e-03
  ENSG00000000419.12      0.1770178 0.1218213 1.13720e-01 2.88125e-01
  ENSG00000000457.13      0.0269533 0.1394669 8.27650e-01 9.21718e-01
  ENSG00000000460.16     -0.0616870 0.2231260 6.92964e-01 8.48743e-01
  ENSG00000000971.15      0.4206549 0.0903614 9.59508e-07 1.36387e-05
                 ...            ...       ...         ...         ...
   ENSG00000285953.1     -1.2313653  0.916996  0.00311401   0.0171889
   ENSG00000285967.1     -0.2623422  0.169901  0.06919688   0.2019448
   ENSG00000285976.1      0.2247352  0.136898  0.06675037   0.1965808
   ENSG00000285979.1      0.1614980  0.257628  0.33148631   0.5713913
   ENSG00000285991.1     -0.0168702  0.290081  0.87313221          NA
  -------
  seqinfo: 25 sequences (1 circular) from hg38 genome</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>ens.str <span class="ot">&lt;-</span> <span class="fu">substr</span>(<span class="fu">names</span>(resGR), <span class="dv">1</span>, <span class="dv">15</span>)</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>resGR<span class="sc">$</span>symbol <span class="ot">&lt;-</span> <span class="fu">mapIds</span>(org.Hs.eg.db, ens.str, <span class="st">"SYMBOL"</span>, <span class="st">"ENSEMBL"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>'select()' returned 1:many mapping between keys and columns</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Gviz)</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a>window <span class="ot">&lt;-</span> resGR[topGene] <span class="sc">+</span> <span class="fl">1e6</span></span>
<span id="cb135-4"><a href="#cb135-4" aria-hidden="true" tabindex="-1"></a><span class="fu">strand</span>(window) <span class="ot">&lt;-</span> <span class="st">"*"</span></span>
<span id="cb135-5"><a href="#cb135-5" aria-hidden="true" tabindex="-1"></a>resGRsub <span class="ot">&lt;-</span> resGR[resGR <span class="sc">%over%</span> window]</span>
<span id="cb135-6"><a href="#cb135-6" aria-hidden="true" tabindex="-1"></a>naOrDup <span class="ot">&lt;-</span> <span class="fu">is.na</span>(resGRsub<span class="sc">$</span>symbol) <span class="sc">|</span> <span class="fu">duplicated</span>(resGRsub<span class="sc">$</span>symbol)</span>
<span id="cb135-7"><a href="#cb135-7" aria-hidden="true" tabindex="-1"></a>resGRsub<span class="sc">$</span>group <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(naOrDup, <span class="fu">names</span>(resGRsub), resGRsub<span class="sc">$</span>symbol)</span>
<span id="cb135-8"><a href="#cb135-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-9"><a href="#cb135-9" aria-hidden="true" tabindex="-1"></a>status <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(resGRsub<span class="sc">$</span>padj <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(resGRsub<span class="sc">$</span>padj),</span>
<span id="cb135-10"><a href="#cb135-10" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"sig"</span>, <span class="st">"notsig"</span>))</span>
<span id="cb135-11"><a href="#cb135-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-12"><a href="#cb135-12" aria-hidden="true" tabindex="-1"></a><span class="do">## gvizplot</span></span>
<span id="cb135-13"><a href="#cb135-13" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">ucscChromosomeNames =</span> <span class="cn">FALSE</span>)</span>
<span id="cb135-14"><a href="#cb135-14" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">GenomeAxisTrack</span>()</span>
<span id="cb135-15"><a href="#cb135-15" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">AnnotationTrack</span>(resGRsub, <span class="at">name =</span> <span class="st">"gene ranges"</span>, <span class="at">feature =</span> status)</span>
<span id="cb135-16"><a href="#cb135-16" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">DataTrack</span>(resGRsub, <span class="at">data =</span> <span class="st">"log2FoldChange"</span>, <span class="at">baseline =</span> <span class="dv">0</span>,</span>
<span id="cb135-17"><a href="#cb135-17" aria-hidden="true" tabindex="-1"></a>               <span class="at">type =</span> <span class="st">"h"</span>, <span class="at">name =</span> <span class="st">"log2 fold change"</span>, <span class="at">strand =</span> <span class="st">"+"</span>)</span>
<span id="cb135-18"><a href="#cb135-18" aria-hidden="true" tabindex="-1"></a><span class="fu">plotTracks</span>(<span class="fu">list</span>(g, d, a), <span class="at">groupAnnotation =</span> <span class="st">"group"</span>,</span>
<span id="cb135-19"><a href="#cb135-19" aria-hidden="true" tabindex="-1"></a>           <span class="at">notsig =</span> <span class="st">"grey"</span>, <span class="at">sig =</span> <span class="st">"hotpink"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="removing-hidden-batch-effects" class="level2">
<h2 class="anchored" data-anchor-id="removing-hidden-batch-effects">Removing hidden batch effects</h2>
<section id="using-sva-with-deseq2" class="level3">
<h3 class="anchored" data-anchor-id="using-sva-with-deseq2">Using SVA with DESeq2</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sva)</span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-3"><a href="#cb136-3" aria-hidden="true" tabindex="-1"></a>dat  <span class="ot">&lt;-</span> <span class="fu">counts</span>(dds, <span class="at">normalized =</span> <span class="cn">TRUE</span>)</span>
<span id="cb136-4"><a href="#cb136-4" aria-hidden="true" tabindex="-1"></a>idx  <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(dat) <span class="sc">&gt;</span> <span class="dv">1</span></span>
<span id="cb136-5"><a href="#cb136-5" aria-hidden="true" tabindex="-1"></a>dat  <span class="ot">&lt;-</span> dat[idx, ]</span>
<span id="cb136-6"><a href="#cb136-6" aria-hidden="true" tabindex="-1"></a>mod  <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span> dex, <span class="fu">colData</span>(dds))</span>
<span id="cb136-7"><a href="#cb136-7" aria-hidden="true" tabindex="-1"></a>mod0 <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span>   <span class="dv">1</span>, <span class="fu">colData</span>(dds))</span>
<span id="cb136-8"><a href="#cb136-8" aria-hidden="true" tabindex="-1"></a>svseq <span class="ot">&lt;-</span> <span class="fu">svaseq</span>(dat, mod, mod0, <span class="at">n.sv =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of significant surrogate variables is:  2 
Iteration (out of 5 ):1  2  3  4  5  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a>svseq<span class="sc">$</span>sv</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           [,1]        [,2]
[1,]  0.2096171 -0.37402683
[2,]  0.2139238 -0.38481049
[3,]  0.1486319 -0.19478674
[4,]  0.1314682 -0.24741213
[5,]  0.2553053  0.53388835
[6,]  0.2569562  0.56828274
[7,] -0.6238462  0.05013275
[8,] -0.5920563  0.04873234</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="do">##svaplot</span></span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">1</span>))</span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>) {</span>
<span id="cb140-4"><a href="#cb140-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stripchart</span>(svseq<span class="sc">$</span>sv[, i] <span class="sc">~</span> dds<span class="sc">$</span>cell, <span class="at">vertical =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"SV"</span>, i))</span>
<span id="cb140-5"><a href="#cb140-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span>
<span id="cb140-6"><a href="#cb140-6" aria-hidden="true" tabindex="-1"></a> }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>ddssva <span class="ot">&lt;-</span> dds</span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>ddssva<span class="sc">$</span>SV1 <span class="ot">&lt;-</span> svseq<span class="sc">$</span>sv[,<span class="dv">1</span>]</span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a>ddssva<span class="sc">$</span>SV2 <span class="ot">&lt;-</span> svseq<span class="sc">$</span>sv[,<span class="dv">2</span>]</span>
<span id="cb141-4"><a href="#cb141-4" aria-hidden="true" tabindex="-1"></a><span class="fu">design</span>(ddssva) <span class="ot">&lt;-</span> <span class="er">~</span> SV1 <span class="sc">+</span> SV2 <span class="sc">+</span> dex</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="using-ruv-with-deseq2" class="level3">
<h3 class="anchored" data-anchor-id="using-ruv-with-deseq2">Using RUV with DESeq2</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RUVSeq)</span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-3"><a href="#cb142-3" aria-hidden="true" tabindex="-1"></a>set <span class="ot">&lt;-</span> <span class="fu">newSeqExpressionSet</span>(<span class="fu">counts</span>(dds))</span>
<span id="cb142-4"><a href="#cb142-4" aria-hidden="true" tabindex="-1"></a>idx  <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(<span class="fu">counts</span>(set) <span class="sc">&gt;</span> <span class="dv">5</span>) <span class="sc">&gt;=</span> <span class="dv">2</span></span>
<span id="cb142-5"><a href="#cb142-5" aria-hidden="true" tabindex="-1"></a>set  <span class="ot">&lt;-</span> set[idx, ]</span>
<span id="cb142-6"><a href="#cb142-6" aria-hidden="true" tabindex="-1"></a>set <span class="ot">&lt;-</span> <span class="fu">betweenLaneNormalization</span>(set, <span class="at">which=</span><span class="st">"upper"</span>)</span>
<span id="cb142-7"><a href="#cb142-7" aria-hidden="true" tabindex="-1"></a>not.sig <span class="ot">&lt;-</span> <span class="fu">rownames</span>(res)[<span class="fu">which</span>(res<span class="sc">$</span>pvalue <span class="sc">&gt;</span> .<span class="dv">1</span>)]</span>
<span id="cb142-8"><a href="#cb142-8" aria-hidden="true" tabindex="-1"></a>empirical <span class="ot">&lt;-</span> <span class="fu">rownames</span>(set)[ <span class="fu">rownames</span>(set) <span class="sc">%in%</span> not.sig ]</span>
<span id="cb142-9"><a href="#cb142-9" aria-hidden="true" tabindex="-1"></a>set <span class="ot">&lt;-</span> <span class="fu">RUVg</span>(set, empirical, <span class="at">k=</span><span class="dv">2</span>)</span>
<span id="cb142-10"><a href="#cb142-10" aria-hidden="true" tabindex="-1"></a><span class="fu">pData</span>(set)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   W_1           W_2
SRR1039508 -0.26933276  0.4109938600
SRR1039509 -0.28309027  0.5195974173
SRR1039512  0.01260963  0.0211629252
SRR1039513 -0.14401331  0.0865517386
SRR1039516  0.58465966  0.0131477643
SRR1039517  0.59835009  0.0001659118
SRR1039520 -0.21813265 -0.5302085106
SRR1039521 -0.28105040 -0.5214111067</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ruvplot</span></span>
<span id="cb144-2"><a href="#cb144-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">1</span>))</span>
<span id="cb144-3"><a href="#cb144-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>) {</span>
<span id="cb144-4"><a href="#cb144-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stripchart</span>(<span class="fu">pData</span>(set)[, i] <span class="sc">~</span> dds<span class="sc">$</span>cell, <span class="at">vertical =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"W"</span>, i))</span>
<span id="cb144-5"><a href="#cb144-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span>
<span id="cb144-6"><a href="#cb144-6" aria-hidden="true" tabindex="-1"></a> }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a>ddsruv <span class="ot">&lt;-</span> dds</span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>ddsruv<span class="sc">$</span>W1 <span class="ot">&lt;-</span> set<span class="sc">$</span>W_1</span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a>ddsruv<span class="sc">$</span>W2 <span class="ot">&lt;-</span> set<span class="sc">$</span>W_2</span>
<span id="cb145-4"><a href="#cb145-4" aria-hidden="true" tabindex="-1"></a><span class="fu">design</span>(ddsruv) <span class="ot">&lt;-</span> <span class="er">~</span> W1 <span class="sc">+</span> W2 <span class="sc">+</span> dex</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="time-course-experiments" class="level2">
<h2 class="anchored" data-anchor-id="time-course-experiments">Time course experiments</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fission)</span>
<span id="cb146-2"><a href="#cb146-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"fission"</span>)</span>
<span id="cb146-3"><a href="#cb146-3" aria-hidden="true" tabindex="-1"></a>ddsTC <span class="ot">&lt;-</span> <span class="fu">DESeqDataSet</span>(fission, <span class="sc">~</span> strain <span class="sc">+</span> minute <span class="sc">+</span> strain<span class="sc">:</span>minute)</span>
<span id="cb146-4"><a href="#cb146-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-5"><a href="#cb146-5" aria-hidden="true" tabindex="-1"></a><span class="do">## fissionDE</span></span>
<span id="cb146-6"><a href="#cb146-6" aria-hidden="true" tabindex="-1"></a>ddsTC <span class="ot">&lt;-</span> <span class="fu">DESeq</span>(ddsTC, <span class="at">test=</span><span class="st">"LRT"</span>, <span class="at">reduced =</span> <span class="sc">~</span> strain <span class="sc">+</span> minute)</span>
<span id="cb146-7"><a href="#cb146-7" aria-hidden="true" tabindex="-1"></a>resTC <span class="ot">&lt;-</span> <span class="fu">results</span>(ddsTC)</span>
<span id="cb146-8"><a href="#cb146-8" aria-hidden="true" tabindex="-1"></a>resTC<span class="sc">$</span>symbol <span class="ot">&lt;-</span> <span class="fu">mcols</span>(ddsTC)<span class="sc">$</span>symbol</span>
<span id="cb146-9"><a href="#cb146-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(resTC[<span class="fu">order</span>(resTC<span class="sc">$</span>padj),], <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>log2 fold change (MLE): strainmut.minute180 
LRT p-value: '~ strain + minute + strain:minute' vs '~ strain + minute' 
DataFrame with 4 rows and 7 columns
              baseMean log2FoldChange     lfcSE      stat      pvalue
             &lt;numeric&gt;      &lt;numeric&gt; &lt;numeric&gt; &lt;numeric&gt;   &lt;numeric&gt;
SPBC2F12.09c   174.671     -2.6567195  0.752261   97.2834 1.97415e-19
SPAC1002.18    444.505     -0.0509321  0.204299   56.9536 5.16955e-11
SPAC1002.19    336.373     -0.3927490  0.573494   43.5339 2.87980e-08
SPAC1002.17c   261.773     -1.1387648  0.606129   39.3158 2.05137e-07
                    padj      symbol
               &lt;numeric&gt; &lt;character&gt;
SPBC2F12.09c 1.33453e-15       atf21
SPAC1002.18  1.74731e-07        urg3
SPAC1002.19  6.48916e-05        urg1
SPAC1002.17c 3.46682e-04        urg2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a>fiss <span class="ot">&lt;-</span> <span class="fu">plotCounts</span>(ddsTC, <span class="fu">which.min</span>(resTC<span class="sc">$</span>padj), </span>
<span id="cb148-2"><a href="#cb148-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">intgroup =</span> <span class="fu">c</span>(<span class="st">"minute"</span>,<span class="st">"strain"</span>), <span class="at">returnData =</span> <span class="cn">TRUE</span>)</span>
<span id="cb148-3"><a href="#cb148-3" aria-hidden="true" tabindex="-1"></a>fiss<span class="sc">$</span>minute <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(fiss<span class="sc">$</span>minute))</span>
<span id="cb148-4"><a href="#cb148-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(fiss,</span>
<span id="cb148-5"><a href="#cb148-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> minute, <span class="at">y =</span> count, <span class="at">color =</span> strain, <span class="at">group =</span> strain)) <span class="sc">+</span> </span>
<span id="cb148-6"><a href="#cb148-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_summary</span>(<span class="at">fun.y=</span>mean, <span class="at">geom=</span><span class="st">"line"</span>) <span class="sc">+</span></span>
<span id="cb148-7"><a href="#cb148-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resultsNames</span>(ddsTC)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Intercept"           "strain_mut_vs_wt"    "minute_15_vs_0"     
 [4] "minute_30_vs_0"      "minute_60_vs_0"      "minute_120_vs_0"    
 [7] "minute_180_vs_0"     "strainmut.minute15"  "strainmut.minute30" 
[10] "strainmut.minute60"  "strainmut.minute120" "strainmut.minute180"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a>res30 <span class="ot">&lt;-</span> <span class="fu">results</span>(ddsTC, <span class="at">name=</span><span class="st">"strainmut.minute30"</span>, <span class="at">test=</span><span class="st">"Wald"</span>)</span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a>res30[<span class="fu">which.min</span>(res30<span class="sc">$</span>padj),]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>log2 fold change (MLE): strainmut.minute30 
Wald test p-value: strainmut.minute30 
DataFrame with 1 row and 6 columns
              baseMean log2FoldChange     lfcSE      stat      pvalue      padj
             &lt;numeric&gt;      &lt;numeric&gt; &lt;numeric&gt; &lt;numeric&gt;   &lt;numeric&gt; &lt;numeric&gt;
SPBC2F12.09c   174.671       -2.60047  0.634343  -4.09947 4.14099e-05  0.279931</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a>betas <span class="ot">&lt;-</span> <span class="fu">coef</span>(ddsTC)</span>
<span id="cb153-2"><a href="#cb153-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(betas)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Intercept"           "strain_mut_vs_wt"    "minute_15_vs_0"     
 [4] "minute_30_vs_0"      "minute_60_vs_0"      "minute_120_vs_0"    
 [7] "minute_180_vs_0"     "strainmut.minute15"  "strainmut.minute30" 
[10] "strainmut.minute60"  "strainmut.minute120" "strainmut.minute180"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="do">##fissionheatmap</span></span>
<span id="cb155-2"><a href="#cb155-2" aria-hidden="true" tabindex="-1"></a>topGenes <span class="ot">&lt;-</span> <span class="fu">head</span>(<span class="fu">order</span>(resTC<span class="sc">$</span>padj),<span class="dv">20</span>)</span>
<span id="cb155-3"><a href="#cb155-3" aria-hidden="true" tabindex="-1"></a>mat <span class="ot">&lt;-</span> betas[topGenes, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)]</span>
<span id="cb155-4"><a href="#cb155-4" aria-hidden="true" tabindex="-1"></a>thr <span class="ot">&lt;-</span> <span class="dv">3</span> </span>
<span id="cb155-5"><a href="#cb155-5" aria-hidden="true" tabindex="-1"></a>mat[mat <span class="sc">&lt;</span> <span class="sc">-</span>thr] <span class="ot">&lt;-</span> <span class="sc">-</span>thr</span>
<span id="cb155-6"><a href="#cb155-6" aria-hidden="true" tabindex="-1"></a>mat[mat <span class="sc">&gt;</span> thr] <span class="ot">&lt;-</span> thr</span>
<span id="cb155-7"><a href="#cb155-7" aria-hidden="true" tabindex="-1"></a><span class="fu">pheatmap</span>(mat, <span class="at">breaks=</span><span class="fu">seq</span>(<span class="at">from=</span><span class="sc">-</span>thr, <span class="at">to=</span>thr, <span class="at">length=</span><span class="dv">101</span>),</span>
<span id="cb155-8"><a href="#cb155-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">cluster_col=</span><span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-47-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="session-information" class="level2">
<h2 class="anchored" data-anchor-id="session-information">Session information</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb156"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb156-1"><a href="#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.5.3 (2026-03-11 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 26200)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] grid      stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] GenomicFeatures_1.62.0      fission_1.30.0             
 [3] RUVSeq_1.44.0               edgeR_4.8.2                
 [5] limma_3.66.0                EDASeq_2.44.0              
 [7] ShortRead_1.68.0            GenomicAlignments_1.46.0   
 [9] Rsamtools_2.26.0            Biostrings_2.78.0          
[11] XVector_0.50.0              sva_3.58.0                 
[13] BiocParallel_1.44.0         mgcv_1.9-4                 
[15] nlme_3.1-168                Gviz_1.54.0                
[17] org.Hs.eg.db_3.22.0         AnnotationDbi_1.72.0       
[19] genefilter_1.92.0           apeglm_1.32.0              
[21] ggbeeswarm_0.7.3            glmpca_0.2.0               
[23] PoiClaClu_1.0.2.1           DESeq2_1.50.2              
[25] tximeta_1.28.3              airway_1.30.0              
[27] SummarizedExperiment_1.40.0 Biobase_2.70.0             
[29] GenomicRanges_1.62.1        Seqinfo_1.0.0              
[31] IRanges_2.44.0              S4Vectors_0.48.0           
[33] BiocGenerics_0.56.0         generics_0.1.4             
[35] MatrixGenerics_1.22.0       matrixStats_1.5.0          
[37] RColorBrewer_1.1-3          pheatmap_1.0.13            
[39] ggplot2_4.0.2               dplyr_1.2.0                
[41] magrittr_2.0.4             

loaded via a namespace (and not attached):
  [1] splines_4.5.3            BiocIO_1.20.0            bitops_1.0-9            
  [4] filelock_1.0.3           R.oo_1.27.1              tibble_3.3.1            
  [7] XML_3.99-0.22            rpart_4.1.24             lifecycle_1.0.5         
 [10] httr2_1.2.2              pwalign_1.6.0            vroom_1.7.0             
 [13] lattice_0.22-9           ensembldb_2.34.0         MASS_7.3-65             
 [16] backports_1.5.0          Hmisc_5.2-5              rmarkdown_2.30          
 [19] yaml_2.3.12              otel_0.2.0               DBI_1.3.0               
 [22] abind_1.4-8              purrr_1.2.1              R.utils_2.13.0          
 [25] AnnotationFilter_1.34.0  biovizBase_1.58.0        RCurl_1.98-1.17         
 [28] nnet_7.3-20              VariantAnnotation_1.56.0 rappdirs_0.3.4          
 [31] annotate_1.88.0          codetools_0.2-20         DelayedArray_0.36.0     
 [34] tidyselect_1.2.1         UCSC.utils_1.6.1         farver_2.1.2            
 [37] BiocFileCache_3.0.0      base64enc_0.1-6          jsonlite_2.0.0          
 [40] Formula_1.2-5            survival_3.8-6           bbmle_1.0.25.1          
 [43] tools_4.5.3              progress_1.2.3           Rcpp_1.1.1              
 [46] glue_1.8.0               gridExtra_2.3            SparseArray_1.10.8      
 [49] xfun_0.56                GenomeInfoDb_1.46.2      withr_3.0.2             
 [52] numDeriv_2016.8-1.1      BiocManager_1.30.27      fastmap_1.2.0           
 [55] latticeExtra_0.6-31      digest_0.6.39            R6_2.6.1                
 [58] colorspace_2.1-2         jpeg_0.1-11              dichromat_2.0-0.1       
 [61] biomaRt_2.66.1           RSQLite_2.4.6            R.methodsS3_1.8.2       
 [64] cigarillo_1.0.0          hexbin_1.28.5            data.table_1.18.2.1     
 [67] rtracklayer_1.70.1       prettyunits_1.2.0        httr_1.4.8              
 [70] htmlwidgets_1.6.4        S4Arrays_1.10.1          pkgconfig_2.0.3         
 [73] gtable_0.3.6             blob_1.3.0               hwriter_1.3.2.1         
 [76] S7_0.2.1                 htmltools_0.5.9          ProtGenerics_1.42.0     
 [79] scales_1.4.0             png_0.1-8                knitr_1.51              
 [82] rstudioapi_0.18.0        tzdb_0.5.0               rjson_0.2.23            
 [85] coda_0.19-4.1            checkmate_2.3.4          curl_7.0.0              
 [88] bdsmatrix_1.3-7          cachem_1.1.0             stringr_1.6.0           
 [91] BiocVersion_3.22.0       parallel_4.5.3           vipor_0.4.7             
 [94] foreign_0.8-91           restfulr_0.0.16          pillar_1.11.1           
 [97] vctrs_0.7.1              dbplyr_2.5.2             xtable_1.8-8            
[100] cluster_2.1.8.2          beeswarm_0.4.0           htmlTable_2.4.3         
[103] tximport_1.38.2          evaluate_1.0.5           readr_2.2.0             
[106] mvtnorm_1.3-3            cli_3.6.5                locfit_1.5-9.12         
[109] compiler_4.5.3           rlang_1.1.7              crayon_1.5.3            
[112] labeling_0.4.3           aroma.light_3.40.0       interp_1.1-6            
[115] emdbook_1.3.14           plyr_1.8.9               stringi_1.8.7           
[118] deldir_2.0-4             txdbmaker_1.6.2          lazyeval_0.2.2          
[121] Matrix_1.7-4             BSgenome_1.78.0          hms_1.1.4               
[124] bit64_4.6.0-1            KEGGREST_1.50.0          statmod_1.5.1           
[127] AnnotationHub_4.0.0      memoise_2.0.1            bit_4.6.0               </code></pre>
</div>
</div>
<section id="references" class="level3 unnumbered">


</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-anders_differential_2010" class="csl-entry" role="listitem">
Anders, Simon, and Wolfgang Huber. 2010. <span>“Differential Expression Analysis for Sequence Count Data.”</span> <em>Genome Biology</em> 11 (10): R106. <a href="https://doi.org/10.1186/gb-2010-11-10-r106">https://doi.org/10.1186/gb-2010-11-10-r106</a>.
</div>
<div id="ref-bache_magrittr_2014" class="csl-entry" role="listitem">
Bache, Stefan Milton, and Hadley Wickham. 2014. <span>“Magrittr: <span>A</span> <span>Forward</span>-<span>Pipe</span> <span>Operator</span> for <span>R</span>.”</span> <a href="https://doi.org/10.32614/CRAN.package.magrittr">https://doi.org/10.32614/CRAN.package.magrittr</a>.
</div>
<div id="ref-carlson_orghsegdb_2017" class="csl-entry" role="listitem">
Carlson, Marc. 2017. <span>“Org.<span>Hs</span>.eg.db.”</span> Bioconductor. <a href="https://doi.org/10.18129/B9.BIOC.ORG.HS.EG.DB">https://doi.org/10.18129/B9.BIOC.ORG.HS.EG.DB</a>.
</div>
<div id="ref-daniela_witten_poiclaclu_2011" class="csl-entry" role="listitem">
Daniela Witten. 2011. <span>“<span>PoiClaClu</span>: <span>Classification</span> and <span>Clustering</span> of <span>Sequencing</span> <span>Data</span> <span>Based</span> on a <span>Poisson</span> <span>Model</span>.”</span> <a href="https://doi.org/10.32614/CRAN.package.PoiClaClu">https://doi.org/10.32614/CRAN.package.PoiClaClu</a>.
</div>
<div id="ref-herve_pages_annotationdbi_2017" class="csl-entry" role="listitem">
Hervé Pagès, Marc Carlson. 2017. <span>“<span>AnnotationDbi</span>.”</span> Bioconductor. <a href="https://doi.org/10.18129/B9.BIOC.ANNOTATIONDBI">https://doi.org/10.18129/B9.BIOC.ANNOTATIONDBI</a>.
</div>
<div id="ref-himes_rna-seq_2014" class="csl-entry" role="listitem">
Himes, Blanca E., Xiaofeng Jiang, Peter Wagner, Ruoxi Hu, Qiyu Wang, Barbara Klanderman, Reid M. Whitaker, et al. 2014. <span>“<span>RNA</span>-<span>Seq</span> Transcriptome Profiling Identifies <span>CRISPLD2</span> as a Glucocorticoid Responsive Gene That Modulates Cytokine Function in Airway Smooth Muscle Cells.”</span> <em>PloS One</em> 9 (6): e99625. <a href="https://doi.org/10.1371/journal.pone.0099625">https://doi.org/10.1371/journal.pone.0099625</a>.
</div>
<div id="ref-kolde_pheatmap_2010" class="csl-entry" role="listitem">
Kolde, Raivo. 2010. <span>“Pheatmap: <span>Pretty</span> <span>Heatmaps</span>.”</span> <a href="https://doi.org/10.32614/CRAN.package.pheatmap">https://doi.org/10.32614/CRAN.package.pheatmap</a>.
</div>
<div id="ref-love_rna-seq_2016" class="csl-entry" role="listitem">
Love, Michael I., Simon Anders, Vladislav Kim, and Wolfgang Huber. 2016. <span>“<span>RNA</span>-<span>Seq</span> Workflow: Gene-Level Exploratory Analysis and Differential Expression.”</span> <em>F1000Research</em> 4 (November): 1070. <a href="https://doi.org/10.12688/f1000research.7035.2">https://doi.org/10.12688/f1000research.7035.2</a>.
</div>
<div id="ref-love_moderated_2014" class="csl-entry" role="listitem">
Love, Michael I, Wolfgang Huber, and Simon Anders. 2014. <span>“Moderated Estimation of Fold Change and Dispersion for <span>RNA</span>-Seq Data with <span>DESeq2</span>.”</span> <em>Genome Biology</em> 15 (12): 550. <a href="https://doi.org/10.1186/s13059-014-0550-8">https://doi.org/10.1186/s13059-014-0550-8</a>.
</div>
<div id="ref-love_tximeta_2020" class="csl-entry" role="listitem">
Love, Michael I., Charlotte Soneson, Peter F. Hickey, Lisa K. Johnson, N. Tessa Pierce, Lori Shepherd, Martin Morgan, and Rob Patro. 2020. <span>“Tximeta: <span>Reference</span> Sequence Checksums for Provenance Identification in <span>RNA</span>-Seq.”</span> Edited by Mihaela Pertea. <em>PLOS Computational Biology</em> 16 (2): e1007664. <a href="https://doi.org/10.1371/journal.pcbi.1007664">https://doi.org/10.1371/journal.pcbi.1007664</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>